/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package main.ui;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.dao.TaiKhoanDAO;
import main.dao.ThongTinNguoiThueDAO;
import main.entity.TaiKhoan;
import main.entity.ThongTinNguoiThue;
import main.impl.TaiKhoanDAOImpl;
import main.impl.ThongTinNguoiThueDAOImpl;
import main.util.XAuth;
import main.util.XDialog;

/**
 *
 * @author PHONG
 */
public class dangnhap extends javax.swing.JDialog implements dangnhapController{

    /**
     * Creates new form dangnhap
     */
    public dangnhap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);  // Ẩn viền và nút X
        initComponents();       

        open(); // nếu cần set vị trí trung tâm
    }
        @Override 
public void open() { 
    this.setLocationRelativeTo(null); 
} 
 
ThongTinNguoiThueDAO thongTinDAO = new ThongTinNguoiThueDAOImpl();

@Override
public void login() {
    String username = txtUsername.getText().trim();
    String password = txtPassword.getText().trim(); 

    if (username.isEmpty() || password.isEmpty()) {
//        XDialog.alert("Tên đăng nhập và mật khẩu không được để trống!");
ImageIcon icon = new ImageIcon(getClass().getResource("/main/icon/problem.png")); // đường dẫn đúng trong resources
JOptionPane.showMessageDialog(this, "Tên đăng nhập và mật khẩu không được để trống!", "Thông báo!", JOptionPane.WARNING_MESSAGE, icon);

        return;
    }

    TaiKhoanDAO dao = new TaiKhoanDAOImpl();
    TaiKhoan user = dao.findById(username);

    if (user == null) {
        XDialog.alert("Tài khoản không tồn tại!");
    } else if (!password.equals(user.getMatKhau())) {
        XDialog.alert("Mật khẩu không đúng!");
    } else {
        // Gán user cho XAuth để sử dụng toàn hệ thống
        XAuth.user = user;

        // Nếu là người thuê thì lấy thêm thông tin người thuê
        if (!user.isVaiTro()) { // false = người thuê
            ThongTinNguoiThueDAO thongTinDAO = new ThongTinNguoiThueDAOImpl();
            ThongTinNguoiThue thongTin = thongTinDAO.findByTenDangNhap(username);

            if (thongTin != null) {
                System.out.println("Đăng nhập thành công: " + thongTin.getHoVaTen());
                System.out.println("Ảnh đại diện: " + thongTin.getPhoto());
                // bạn có thể gán vào MainForm nếu cần
            } else {
                System.out.println("Đăng nhập thành công, nhưng chưa có thông tin người thuê!");
            }
        } else {
            // Admin
            System.out.println("Đăng nhập thành công: Quản trị viên");
        }

        // Đóng form
        this.dispose();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btndong = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jTShow = new javax.swing.JToggleButton();
        btnDangNhap = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        rememberMeCheckbox = new javax.swing.JCheckBox();
        lblQuenMK = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 191, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NHÀ TRỌ FPOLY");

        btndong.setBackground(new java.awt.Color(0, 0, 255));
        btndong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btndong.setForeground(new java.awt.Color(255, 255, 255));
        btndong.setText("X");
        btndong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/houselogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndong, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btndong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 60));

        jLabel4.setBackground(new java.awt.Color(0, 0, 139));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("ĐĂNG NHẬP");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 139));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tên đăng nhập");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 139));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Mật khẩu");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(40, 46, 62));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 230, 25));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(40, 46, 62));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 184, 25));

        jTShow.setBackground(new java.awt.Color(153, 153, 255));
        jTShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/view.png"))); // NOI18N
        jTShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTShowMouseClicked(evt);
            }
        });
        jTShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTShowActionPerformed(evt);
            }
        });
        jPanel1.add(jTShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 25));

        btnDangNhap.setBackground(new java.awt.Color(102, 204, 255));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(40, 46, 62));
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, 43));

        btnDangKy.setBackground(new java.awt.Color(102, 204, 255));
        btnDangKy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(40, 46, 62));
        btnDangKy.setText("ĐĂNG KÝ ");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 118, 43));

        rememberMeCheckbox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rememberMeCheckbox.setText("Remember Me");
        rememberMeCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberMeCheckboxActionPerformed(evt);
            }
        });
        jPanel1.add(rememberMeCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        lblQuenMK.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblQuenMK.setForeground(new java.awt.Color(100, 100, 100));
        lblQuenMK.setText("Quên mật khẩu?");
        lblQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseClicked(evt);
            }
        });
        jPanel1.add(lblQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/dangnhap.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 145, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/nen1.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(3000, 168));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        this.showdangkyJDialog((JFrame) this.getOwner());
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void rememberMeCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberMeCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberMeCheckboxActionPerformed

    private void lblQuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseClicked
        // TODO add your handling code here:
//        this.dispose();
//        QuenMatKhau quenmk = new QuenMatKhau();
//        quenmk.setVisible(true);
    }//GEN-LAST:event_lblQuenMKMouseClicked

    private void jTShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTShowActionPerformed

    private void jTShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTShowMouseClicked
        if (jTShow.isSelected()) {
            txtPassword.setEchoChar((char) 0);
//            jTShow.setBackground(new Color(255,205,31));
            jTShow.setIcon(new ImageIcon(getClass().getResource("/main/icon/hide.png")));
        } else {
            txtPassword.setEchoChar('\u25cf');
//            jTShow.setBackground(new Color(255,205,31));
            jTShow.setIcon(new ImageIcon(getClass().getResource("/main/icon/view.png")));
        }
    }//GEN-LAST:event_jTShowMouseClicked

    private void btndongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn muốn đóng ứng dụng?", "Thoát?", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btndongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dangnhap dialog = new dangnhap(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btndong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jTShow;
    private javax.swing.JLabel lblQuenMK;
    private javax.swing.JCheckBox rememberMeCheckbox;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
