/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.ui;

import main.dao.ThongTinNguoiThueDAO;
import main.entity.ThongTinNguoiThue;
import main.impl.ThongTinNguoiThueDAOImpl;
import main.util.XAuth;
import main.util.XIcon;

/**
 *
 * @author PHONG
 */
public class quanlynhatro extends javax.swing.JFrame implements quanlynhatroController{

    /**
     * Creates new form quanlynhatro
     */
    public quanlynhatro() {
        initComponents();
        this.init();
        ManagerButtons();
    }
    

    @Override
    public void init() {
        this.setIconImage(XIcon.getIcon("avartar.jpg").getImage());
        this.setLocationRelativeTo(null);

        this.showWelcomeJDialog(this);
        this.showLoginJDialog(this);

        // Hiển thị thông tin người dùng
        if (XAuth.user != null) {
if (!XAuth.user.isVaiTro()) {
    // Nếu là người thuê thì lấy thêm thông tin từ bảng ThongTinNguoiThue
    ThongTinNguoiThueDAO thongTinDAO = new ThongTinNguoiThueDAOImpl();
    ThongTinNguoiThue thongTin = thongTinDAO.findByTenDangNhap(XAuth.user.getTenDangNhap());

    if (thongTin != null) {
        lblfullname.setText(thongTin.getHoVaTen());
        XIcon.setIcon(lblphoto, "D:/code/java/QUANLYNHATRO/src/main/resources/main/icon/" + thongTin.getPhoto());
    } else {
        lblfullname.setText("Người dùng");
        XIcon.setIcon(lblphoto, "D:/code/java/QUANLYNHATRO/src/main/resources/main/icon/photo.png");
    }

    // Ẩn các chức năng của admin
    jPanel1.setVisible(false);
} else {
    // Nếu là admin
    lblfullname.setText("Quản trị viên");
    XIcon.setIcon(lblphoto, "D:/code/java/QUANLYNHATRO/src/main/resources/main/icon/admin.png");
}


            // Ẩn toàn bộ panel quản trị nếu không phải admin
            if (!XAuth.user.isVaiTro()) {
                jPanel1.setVisible(false); // hoặc bạn có thể remove nếu muốn
            }
        }
    }



public void ManagerButtons() {
    jPanel2.setVisible(true);

    if (!XAuth.isLogin()) {
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        return;
    }

    if (XAuth.user.isVaiTro()) {
        jPanel3.setVisible(false); 
        btnquanlytaikhoan.setVisible(true);
        btnquanlyphong.setVisible(true);
        btnquanlyhoadon.setVisible(true);
        btnquanlyhopdong.setVisible(true);
        btnquanlykhachthue.setVisible(true);
        btndoanhthu.setVisible(true);

        jPanel1.setVisible(true); 

    } else {
        jPanel1.setVisible(true);

        
        btnquanlytaikhoan.setVisible(false);
        btnquanlyphong.setVisible(false);
        btnquanlyhoadon.setVisible(false);
        btnquanlyhopdong.setVisible(false);
        btnquanlykhachthue.setVisible(false);
        btndoanhthu.setVisible(false);
        jPanel3.setVisible(true);
        btnthongtinnguoithue.setVisible(true);
        btnxemhoadon.setVisible(true);
        btnxemphong.setVisible(true);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnquanlykhachthue = new javax.swing.JButton();
        btnquanlyhopdong = new javax.swing.JButton();
        btnquanlytaikhoan = new javax.swing.JButton();
        btnquanlyphong = new javax.swing.JButton();
        btnquanlyhoadon = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnthongtinnguoithue = new javax.swing.JButton();
        btnxemhoadon = new javax.swing.JButton();
        btnxemphong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btndoimatkhau = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btndoanhthu = new javax.swing.JButton();
        btnketthuc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblphoto = new javax.swing.JLabel();
        lblfullname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnquanlykhachthue.setText("Quản Lý Khách Thuê");
        btnquanlykhachthue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlykhachthueActionPerformed(evt);
            }
        });
        jPanel1.add(btnquanlykhachthue, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 140, 60));

        btnquanlyhopdong.setText("Quản Lý Hợp Đồng");
        btnquanlyhopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlyhopdongActionPerformed(evt);
            }
        });
        jPanel1.add(btnquanlyhopdong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 140, 60));

        btnquanlytaikhoan.setText("Quản Lý Tài Khoản");
        btnquanlytaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlytaikhoanActionPerformed(evt);
            }
        });
        jPanel1.add(btnquanlytaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 50));

        btnquanlyphong.setText("Quản Lý Phòng");
        btnquanlyphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlyphongActionPerformed(evt);
            }
        });
        jPanel1.add(btnquanlyphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 50));

        btnquanlyhoadon.setText("Quản Lý Hóa Đơn");
        btnquanlyhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlyhoadonActionPerformed(evt);
            }
        });
        jPanel1.add(btnquanlyhoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 130, 50));

        jPanel3.setBackground(new java.awt.Color(255, 0, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnthongtinnguoithue.setText("Thông Tin Người Thuê");
        btnthongtinnguoithue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongtinnguoithueActionPerformed(evt);
            }
        });
        jPanel3.add(btnthongtinnguoithue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 150, 120));

        btnxemhoadon.setText("Xem Hóa Đơn");
        btnxemhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxemhoadonActionPerformed(evt);
            }
        });
        jPanel3.add(btnxemhoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 120, 120));

        btnxemphong.setText("Xem Phòng");
        btnxemphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxemphongActionPerformed(evt);
            }
        });
        jPanel3.add(btnxemphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 120));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 429, 140));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 139));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndoimatkhau.setText("Đổi Mật Khẩu");
        btndoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoimatkhauActionPerformed(evt);
            }
        });
        jPanel2.add(btndoimatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 50));

        jButton7.setText("Lịch Sử");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 50));

        btndoanhthu.setText("Doanh Thu");
        btndoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoanhthuActionPerformed(evt);
            }
        });
        jPanel2.add(btndoanhthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 90, 50));

        btnketthuc.setText("Kết Thúc");
        btnketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketthucActionPerformed(evt);
            }
        });
        jPanel2.add(btnketthuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 100, 50));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 429, 72));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Nhà Trọ DESTINY");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 420, -1));

        lblphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/avartar.jpg"))); // NOI18N
        jPanel4.add(lblphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 188, 184));

        lblfullname.setBackground(new java.awt.Color(51, 51, 51));
        lblfullname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblfullname.setForeground(new java.awt.Color(255, 0, 0));
        lblfullname.setText("PHONG HUYNH");
        jPanel4.add(lblfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/download.jpg"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoimatkhauActionPerformed
        // TODO add your handling code here:
                new doimatkhauJdialog(this, true).setVisible(true);
    }//GEN-LAST:event_btndoimatkhauActionPerformed

    private void btnquanlytaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlytaikhoanActionPerformed
        // TODO add your handling code here:
        showquanlytaikhoanJdialog(this);
    }//GEN-LAST:event_btnquanlytaikhoanActionPerformed

    private void btnquanlyphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlyphongActionPerformed
        // TODO add your handling code here:
        showquanlyphongJdialog(this);
    }//GEN-LAST:event_btnquanlyphongActionPerformed

    private void btnquanlyhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlyhoadonActionPerformed
        // TODO add your handling code here:
        showquanlyhoadonJdialog(this);
    }//GEN-LAST:event_btnquanlyhoadonActionPerformed

    private void btnquanlyhopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlyhopdongActionPerformed
        // TODO add your handling code here:
        showquanlyhopdongJdialog(this);
    }//GEN-LAST:event_btnquanlyhopdongActionPerformed

    private void btnquanlykhachthueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlykhachthueActionPerformed
        // TODO add your handling code here:
        showquanlykhachthueJdialog(this);
    }//GEN-LAST:event_btnquanlykhachthueActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketthucActionPerformed
        // TODO add your handling code here:
        exit(); // Gọi method exit() trong interface để thoát
    }//GEN-LAST:event_btnketthucActionPerformed

    private void btndoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoanhthuActionPerformed
        // TODO add your handling code here:
        showdoanhthuJdialog(this);
    }//GEN-LAST:event_btndoanhthuActionPerformed

    private void btnthongtinnguoithueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongtinnguoithueActionPerformed
        // TODO add your handling code here:
        showthongtinnguoithueJdialog(this);
    }//GEN-LAST:event_btnthongtinnguoithueActionPerformed

    private void btnxemhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxemhoadonActionPerformed
        // TODO add your handling code here:
         showxemhoadonJDialog(this);
    }//GEN-LAST:event_btnxemhoadonActionPerformed

    private void btnxemphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxemphongActionPerformed
        // TODO add your handling code here:
         showxemphongJDialog(this);
    }//GEN-LAST:event_btnxemphongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlynhatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlynhatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlynhatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlynhatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanlynhatro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndoanhthu;
    private javax.swing.JButton btndoimatkhau;
    private javax.swing.JButton btnketthuc;
    private javax.swing.JButton btnquanlyhoadon;
    private javax.swing.JButton btnquanlyhopdong;
    private javax.swing.JButton btnquanlykhachthue;
    private javax.swing.JButton btnquanlyphong;
    private javax.swing.JButton btnquanlytaikhoan;
    private javax.swing.JButton btnthongtinnguoithue;
    private javax.swing.JButton btnxemhoadon;
    private javax.swing.JButton btnxemphong;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblfullname;
    private javax.swing.JLabel lblphoto;
    // End of variables declaration//GEN-END:variables


}
