/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package main.ui;

import java.security.SecureRandom;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import main.entity.TaiKhoan;
import main.impl.TaiKhoanDAOImpl;
import main.util.XMail; // Import lớp XMail từ package main.util



/**
 *
 * @author PHONG
 */
public class quenmatkhauJdialog_1 extends javax.swing.JDialog implements QuenMatKhauController {

    /**
     * Creates new form quenmatkhauJdialog
     */
    public quenmatkhauJdialog_1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        btnDoiPass.setEnabled(false);
        setLocationRelativeTo(null);
    }

    private final Map<String, String> maXacNhanMap = new HashMap<>();
    private final TaiKhoanDAOImpl dao = new TaiKhoanDAOImpl();


    @Override
    public void guiMaXacNhan() {
        String email = txtmail.getText().trim();

        if (email.isEmpty()) {
            showMsg("Vui lòng nhập email!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!emailExists(email)) {
            showMsg("Email này không tồn tại!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String code = generateCode();
        if (XMail.sendMail(email, code)) { // Gọi trực tiếp phương thức sendMail của lớp XMail
            maXacNhanMap.put(email, code);
            showMsg("Mã xác nhận đã gửi về email!", JOptionPane.INFORMATION_MESSAGE);
            btnDoiPass.setEnabled(true);
        } else {
            showMsg("Không gửi được mã xác nhận. Hãy thử lại!", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void doiMatKhau() {
        String email = txtmail.getText().trim();
        String maXacNhan = txtma.getText().trim();
        String newPassword = new String(txtNewPassword.getPassword()).trim();

        if (email.isEmpty() || maXacNhan.isEmpty() || newPassword.isEmpty()) {
            showMsg("Vui lòng nhập đầy đủ thông tin!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!maXacNhan.equals(maXacNhanMap.get(email))) {
            showMsg("Mã xác nhận không đúng hoặc đã hết hạn!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        TaiKhoan tk = getTaiKhoanByEmail(email);
        if (tk == null) {
            showMsg("Không tìm thấy tài khoản với email này!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        tk.setMatKhau(newPassword);
        dao.update(tk);
        showMsg("Đổi mật khẩu thành công! Vui lòng đăng nhập lại.", JOptionPane.INFORMATION_MESSAGE);

        this.dispose();
        new dangnhapJdialog(null, true).setVisible(true);
    }

    // --- HÀM HỖ TRỢ ---
    private boolean emailExists(String email) {
        return dao.findAll().stream().anyMatch(tk -> email.equalsIgnoreCase(tk.getEmail()));
    }

    private TaiKhoan getTaiKhoanByEmail(String email) {
        return dao.findAll().stream()
            .filter(tk -> email.equalsIgnoreCase(tk.getEmail()))
            .findFirst().orElse(null);
    }

    private void showMsg(String msg, int type) {
        JOptionPane.showMessageDialog(this, msg, "Thông báo", type);
    }

    private String generateCode() {
        return String.valueOf(new SecureRandom().nextInt(900_000) + 100_000);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btndong = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btngui = new javax.swing.JButton();
        btnDoiPass = new javax.swing.JButton();
        txtNewPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NHÀ TRỌ FPOLY");

        btndong.setBackground(new java.awt.Color(0, 0, 255));
        btndong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btndong.setForeground(new java.awt.Color(255, 255, 255));
        btndong.setText("X");
        btndong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/houselogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndong, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btndong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 60));

        btngui.setBackground(new java.awt.Color(102, 204, 255));
        btngui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btngui.setForeground(new java.awt.Color(40, 46, 62));
        btngui.setText("Gửi");
        btngui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguiActionPerformed(evt);
            }
        });
        getContentPane().add(btngui, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, 43));

        btnDoiPass.setBackground(new java.awt.Color(102, 204, 255));
        btnDoiPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDoiPass.setForeground(new java.awt.Color(40, 46, 62));
        btnDoiPass.setText("Đổi");
        btnDoiPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiPassActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoiPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 118, 43));

        txtNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNewPassword.setForeground(new java.awt.Color(40, 46, 62));
        getContentPane().add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 190, 25));

        jLabel6.setBackground(new java.awt.Color(0, 0, 139));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Mật khẩu mới:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtmail.setForeground(new java.awt.Color(40, 46, 62));
        getContentPane().add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 190, 25));

        jLabel5.setBackground(new java.awt.Color(0, 0, 139));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 139));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("QUÊN MẬT KHẨU");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        txtma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtma.setForeground(new java.awt.Color(40, 46, 62));
        getContentPane().add(txtma, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 25));

        jLabel8.setBackground(new java.awt.Color(0, 0, 139));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Mã xác nhận:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/nen1.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(3000, 168));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn muốn đóng ứng dụng?", "Thoát?", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btndongActionPerformed

    private void btnguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguiActionPerformed
        // TODO add your handling code here:
        guiMaXacNhan();
    }//GEN-LAST:event_btnguiActionPerformed

    private void btnDoiPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiPassActionPerformed
        // TODO add your handling code here:
        doiMatKhau();
    }//GEN-LAST:event_btnDoiPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJdialog_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJdialog_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJdialog_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJdialog_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                quenmatkhauJdialog_1 dialog = new quenmatkhauJdialog_1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiPass;
    private javax.swing.JButton btndong;
    private javax.swing.JButton btngui;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtmail;
    // End of variables declaration//GEN-END:variables
}
