/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package App.Main;

import App.DAO.TaiKhoanDAO;
import App.Entity.TaiKhoan;
import App.Impl.TaiKhoanDAOImpl;
import App.Utils.XAuth;
import App.Utils.XDialog;
import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

//import main.ui.quanlynhatro;
/**
 *
 * @author PHONG
 */
public class dangnhapJdialog extends javax.swing.JDialog implements dangnhapController{
    
    //kiểm tra đăng nhập
    private boolean dangNhapThanhCong = false; 
    
    public dangnhapJdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);  // Ẩn viền và nút X
        initComponents();
        open();
    }
    
    @Override
    public void open() {
        //form giữa màn hình
        this.setLocationRelativeTo(null);
    }
 
    @Override
    public void login() {
        // Lấy dữ liệu từ ô nhập
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();

        // Kiểm tra nhập trống
        if (username.isEmpty() || password.isEmpty()) {
            XDialog.alert("Tên đăng nhập và mật khẩu không được để trống!");
            return;
        }

        // Tìm tài khoản trong database
        TaiKhoanDAO dao = new TaiKhoanDAOImpl();
        TaiKhoan user = null;
        try {
            user = dao.findByTenTaiKhoanAndMatKhau(username, password);
        } catch (Exception ex) {
            XDialog.alert("Lỗi kết nối dữ liệu: " + ex.getMessage());
            return;
        }

        // Nếu không tìm thấy
        if (user == null) {
            XDialog.alert("Tên đăng nhập hoặc mật khẩu không đúng!");
            return;
        }

        // Kiểm tra trạng thái: 0 = khóa, 1 = hoạt động
        if (user.getTrangThai() != null && user.getTrangThai() == 0) {
            XDialog.alert("Tài khoản đang bị tạm khóa!");
            return;
        }

        // Nếu qua hết kiểm tra => thành công
        XAuth.user = user;
        dangNhapThanhCong = true;
        XDialog.alert("Đăng nhập thành công! Chào mừng " + user.getHoTen());

        // Đóng form đăng nhập
        this.dispose();

        // Tạo biến final để dùng trong lambda
        final TaiKhoan currentUser = user;

        // Mở màn hình chính theo vai trò
        java.awt.EventQueue.invokeLater(() -> {
            try {
                if (Integer.valueOf(1).equals(currentUser.getVaiTro())) {
                    // Vai trò = 1: Admin / Chủ trọ
                    new App.Main.ChuTro.Main_ChuTro().setVisible(true);
                } else {
                    // Người dùng / Người thuê
                    new App.Main.NguoiDung.MainNguoiDung().setVisible(true);
                }
            } catch (Exception e) {
                e.printStackTrace();
                XDialog.alert("Không mở được màn hình chính: " + e.getMessage());
            }
        });
    }

    public boolean isDangNhapThanhCong() {
        return dangNhapThanhCong;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btndong = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        rememberMeCheckbox = new javax.swing.JCheckBox();
        btnDangNhap = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        lblQuenMK = new javax.swing.JLabel();
        jTShow = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NHÀ TRỌ FPOLY");

        btndong.setBackground(new java.awt.Color(0, 0, 255));
        btndong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btndong.setForeground(new java.awt.Color(255, 255, 255));
        btndong.setText("X");
        btndong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(444, 444, 444)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 463, Short.MAX_VALUE)
                .addComponent(btndong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btndong, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 80));

        jLabel4.setBackground(new java.awt.Color(0, 0, 139));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setText("ĐĂNG NHẬP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 139));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Tên đăng nhập:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 139));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Mật khẩu:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, 40));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(40, 46, 62));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 240, 40));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(40, 46, 62));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 190, 40));

        rememberMeCheckbox.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rememberMeCheckbox.setText("Remember Me");
        rememberMeCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberMeCheckboxActionPerformed(evt);
            }
        });
        getContentPane().add(rememberMeCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        btnDangNhap.setBackground(new java.awt.Color(102, 204, 255));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(40, 46, 62));
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 180, 70));

        btnDangKy.setBackground(new java.awt.Color(102, 204, 255));
        btnDangKy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(40, 46, 62));
        btnDangKy.setText("ĐĂNG KÝ ");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 180, 70));

        lblQuenMK.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblQuenMK.setForeground(new java.awt.Color(100, 100, 100));
        lblQuenMK.setText("Quên mật khẩu?");
        lblQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseClicked(evt);
            }
        });
        getContentPane().add(lblQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 360, 180, -1));

        jTShow.setBackground(new java.awt.Color(0, 255, 255));
        jTShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/view.png"))); // NOI18N
        jTShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTShowMouseClicked(evt);
            }
        });
        jTShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTShowActionPerformed(evt);
            }
        });
        getContentPane().add(jTShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/nen02.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(3000, 168));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rememberMeCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberMeCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberMeCheckboxActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:                                            
        login();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        // Ẩn tạm form đăng nhập
        setVisible(false);

        // Mở form đăng ký (đơn giản: không truyền owner)
        dangkyJdialog dk = new dangkyJdialog(null, true);
        dk.setVisible(true);            // modal: chờ tới khi user đóng

        // Hiện lại form đăng nhập sau khi đóng đăng ký
        if (isDisplayable()) {
            setVisible(true);
            toFront();
        } 
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void lblQuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseClicked
        // TODO add your handling code here:
        quenmatkhauJdialog qmk = new quenmatkhauJdialog((java.awt.Frame) getParent(), true);
        qmk.setVisible(true);
    }//GEN-LAST:event_lblQuenMKMouseClicked

    private void jTShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTShowMouseClicked
        // TODO add your handling code here:
        // Đặt màu nền (giống nhau nên đặt chung)
        jTShow.setBackground(new Color(0,255,255));

        if (jTShow.isSelected()) {
            // Hiện mật khẩu
            txtPassword.setEchoChar((char) 0);

            // Đổi icon thành "hide"
            URL hideIconURL = getClass().getResource("/App/Icon/hide.png");
            if (hideIconURL != null) {
                jTShow.setIcon(new ImageIcon(hideIconURL));
            } else {
                System.err.println("Hide icon not found.");
            }
        } else {
            // Ẩn mật khẩu
            txtPassword.setEchoChar('\u2022'); // ký tự chấm tròn

            // Đổi icon thành "view"
            URL viewIconURL = getClass().getResource("/App/Icon/view.png");
            if (viewIconURL != null) {
                jTShow.setIcon(new ImageIcon(viewIconURL));
            } else {
                System.err.println("View icon not found.");
            }
        }
    }//GEN-LAST:event_jTShowMouseClicked

    private void jTShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTShowActionPerformed

    private void btndongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
                this,                             // component cha (cứ dùng this cho dialog)
                "Bạn có chắc muốn thoát ứng dụng?", 
                "Xác nhận thoát", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE       // icon dấu hỏi ? (nhìn đẹp hơn)
        );

        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btndongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangnhapJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangnhapJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangnhapJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangnhapJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dangnhapJdialog dialog = new dangnhapJdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btndong;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jTShow;
    private javax.swing.JLabel lblQuenMK;
    private javax.swing.JCheckBox rememberMeCheckbox;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
