/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package App.Main;

import App.DAO.LichSuNguoiDungDAO;
import App.Entity.LichSuNguoiDung;
import App.Impl.LichSuNguoiDungDAOImpl;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PHONG
 */
public class LichSuNguoiDungJDialog extends javax.swing.JDialog implements LichSuNguoiDungController{


    private final LichSuNguoiDungDAO dao = new LichSuNguoiDungDAOImpl(); // DAO thao tác DB
    private DefaultTableModel model;
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm"); // format ngày giờ
    private Integer filterUserId = null; // nếu mở theo user cụ thể

    // constructor bình thường
    public LichSuNguoiDungJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        afterInit();
        setLocationRelativeTo(null); // căn giữa
    }

    // constructor mở và lọc theo user
    public LichSuNguoiDungJDialog(java.awt.Frame parent, boolean modal, Integer maNguoiDung) {
        super(parent, modal);
        this.filterUserId = maNguoiDung;
        initComponents();
        afterInit();
    }

    // ====== setup bảng sau khi build UI ======
    private void afterInit() {
        model = (DefaultTableModel) tblLichSuHD.getModel();
        model.setColumnIdentifiers(new Object[]{"Mã LS", "Mã người dùng", "Hành động", "Thời gian"});
        tblLichSuHD.setAutoCreateRowSorter(true);

        if (filterUserId != null) {
            loadByUser(filterUserId); // nếu có user thì lọc theo user
        } else {
            loadTable(); // ngược lại load toàn bộ
        }
    }

    // ====== load toàn bộ lịch sử ======
    public void loadTable() {
        model.setRowCount(0); // xóa dữ liệu cũ
        List<LichSuNguoiDung> list = dao.findAll(); // lấy từ DB

        if (list != null) {
            for (LichSuNguoiDung ls : list) {
                String hanhDong = (ls.getHanhDong() == null) ? "" : ls.getHanhDong();
                String thoiGian = (ls.getThoiGian() == null) ? "" : sdf.format(ls.getThoiGian());

                model.addRow(new Object[]{
                    ls.getId(),
                    ls.getMaNguoiDung(),
                    hanhDong,
                    thoiGian
                });
            }
        }
    }

    // ====== load theo 1 user cụ thể ======
    public void loadByUser(Integer userId) {
        model.setRowCount(0);
        List<LichSuNguoiDung> list = dao.findByMaNguoiDung(userId);

        if (list != null) {
            for (LichSuNguoiDung ls : list) {
                String hanhDong = (ls.getHanhDong() == null) ? "" : ls.getHanhDong();
                String thoiGian = (ls.getThoiGian() == null) ? "" : sdf.format(ls.getThoiGian());

                model.addRow(new Object[]{
                    ls.getId(),
                    ls.getMaNguoiDung(),
                    hanhDong,
                    thoiGian
                });
            }
        }
    }

    // ====== tìm kiếm theo từ khóa ======
    public void search(String keyword) {
        String kw = (keyword == null) ? "" : keyword.trim().toLowerCase();

        if (kw.isEmpty()) { 
            if (filterUserId != null) {
                loadByUser(filterUserId);
            } else {
                loadTable();
            }
            return;
        }

        model.setRowCount(0);

        // lấy dữ liệu gốc
        List<LichSuNguoiDung> src;
        if (filterUserId != null) {
            src = dao.findByMaNguoiDung(filterUserId);
        } else {
            src = dao.findAll();
        }

        if (src != null) {
            for (LichSuNguoiDung ls : src) {
                String hanhDong = (ls.getHanhDong() == null) ? "" : ls.getHanhDong();
                String thoiGian = (ls.getThoiGian() == null) ? "" : sdf.format(ls.getThoiGian());

                // gộp dữ liệu để tìm
                String gop = (ls.getMaNguoiDung() + " " + hanhDong + " " + thoiGian).toLowerCase();

                if (gop.contains(kw)) {
                    model.addRow(new Object[]{
                        ls.getId(),
                        ls.getMaNguoiDung(),
                        hanhDong,
                        thoiGian
                    });
                }
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel103 = new javax.swing.JPanel();
        jLabel112 = new javax.swing.JLabel();
        btndong102 = new javax.swing.JButton();
        jLabel113 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLichSuHD = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 46, 62));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel103.setBackground(new java.awt.Color(102, 204, 255));
        jPanel103.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel112.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(255, 255, 255));
        jLabel112.setText("NHÀ TRỌ FPOLY");
        jPanel103.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        btndong102.setBackground(new java.awt.Color(0, 0, 255));
        btndong102.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btndong102.setForeground(new java.awt.Color(255, 255, 255));
        btndong102.setText("X");
        btndong102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndong102ActionPerformed(evt);
            }
        });
        jPanel103.add(btndong102, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 9, 55, 50));

        jLabel113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/logo1.png"))); // NOI18N
        jPanel103.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 3, -1, 62));

        jPanel1.add(jPanel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 205, 31));
        jLabel1.setText("LỊCH SỬ HOẠT ĐỘNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 250, -1));

        tblLichSuHD.setBackground(new java.awt.Color(207, 243, 243));
        tblLichSuHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblLichSuHD.setForeground(new java.awt.Color(40, 46, 62));
        tblLichSuHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLichSuHD.setSelectionBackground(new java.awt.Color(46, 56, 86));
        tblLichSuHD.setSelectionForeground(new java.awt.Color(255, 205, 31));
        jScrollPane1.setViewportView(tblLichSuHD);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 105, 914, 460));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/nen02.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndong102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndong102ActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Bạn muốn đóng cửa sổ này?",
                "Đóng",
                JOptionPane.YES_NO_OPTION
        );
        if (choice == JOptionPane.YES_OPTION) {
            this.dispose(); // chỉ đóng JDialog hiện tại
        }
    }//GEN-LAST:event_btndong102ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LichSuNguoiDungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LichSuNguoiDungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LichSuNguoiDungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LichSuNguoiDungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LichSuNguoiDungJDialog dialog = new LichSuNguoiDungJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndong102;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLichSuHD;
    // End of variables declaration//GEN-END:variables
}
