/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package App.Main;

import App.Entity.TaiKhoan;
import App.Impl.TaiKhoanDAOImpl;
import App.Utils.XMail;
import java.security.SecureRandom;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author PHONG
 */
public class quenmatkhauJdialog extends javax.swing.JDialog implements quenmatkhauController{

    private TaiKhoanDAOImpl dao = new TaiKhoanDAOImpl();
    private String maXacNhan = "";  // Lưu mã xác nhận của người dùng
    
    public quenmatkhauJdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);  // Ẩn viền và nút X
        initComponents();
        open();
    }
    
        @Override
public void open() { 
        btnDoiPass.setEnabled(false); // Ban đầu chưa cho đổi mật khẩu
        setLocationRelativeTo(null);  // Căn giữa màn hình
}


   // Gửi mã xác nhận
    public void guiMaXacNhan() {
        String email = txtmail.getText().trim();

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email!");
            return;
        }

        // Kiểm tra email có tồn tại trong DB không
        TaiKhoan tk = null;
        for (TaiKhoan t : dao.findAll()) {
            if (email.equalsIgnoreCase(t.getEmail())) {
                tk = t;
                break;
            }
        }

        if (tk == null) {
            JOptionPane.showMessageDialog(this, "Email này không tồn tại!");
            return;
        }

        // Sinh mã xác nhận ngẫu nhiên 6 số
        maXacNhan = String.valueOf(new SecureRandom().nextInt(900000) + 100000);

        // Gửi email
        if (XMail.sendMail(email, maXacNhan)) {
            JOptionPane.showMessageDialog(this, "Mã xác nhận đã gửi về email!");
            btnDoiPass.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Không gửi được mã. Thử lại!");
        }
    }

    // Đổi mật khẩu
    public void doiMatKhau() {
        String email = txtmail.getText().trim();
        String maNhap = txtma.getText().trim();
        String matKhauMoi = new String(txtNewPassword.getPassword()).trim();

        if (email.isEmpty() || maNhap.isEmpty() || matKhauMoi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }

        // Kiểm tra mã xác nhận
        if (!maNhap.equals(maXacNhan)) {
            JOptionPane.showMessageDialog(this, "Mã xác nhận không đúng!");
            return;
        }

        // Tìm tài khoản theo email
        TaiKhoan tk = null;
        for (TaiKhoan t : dao.findAll()) {
            if (email.equalsIgnoreCase(t.getEmail())) {
                tk = t;
                break;
            }
        }

        if (tk == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản!");
            return;
        }

        // Cập nhật mật khẩu mới
        tk.setMatKhau(matKhauMoi);
        dao.update(tk);

        JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");
        this.dispose();
        new dangnhapJdialog(null, true).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btndong = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnquaylai = new javax.swing.JButton();
        btngui = new javax.swing.JButton();
        btnDoiPass = new javax.swing.JButton();
        txtNewPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NHÀ TRỌ FPOLY");

        btndong.setBackground(new java.awt.Color(0, 0, 255));
        btndong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btndong.setForeground(new java.awt.Color(255, 255, 255));
        btndong.setText("X");
        btndong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/logo1.png"))); // NOI18N

        btnquaylai.setBackground(new java.awt.Color(0, 0, 255));
        btnquaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/return (1).png"))); // NOI18N
        btnquaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel9)
                .addGap(444, 444, 444)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)
                .addComponent(btnquaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btndong, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)))
                    .addComponent(btnquaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 80));

        btngui.setBackground(new java.awt.Color(102, 204, 255));
        btngui.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btngui.setForeground(new java.awt.Color(40, 46, 62));
        btngui.setText("GỬI");
        btngui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguiActionPerformed(evt);
            }
        });
        getContentPane().add(btngui, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 180, 70));

        btnDoiPass.setBackground(new java.awt.Color(102, 204, 255));
        btnDoiPass.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDoiPass.setForeground(new java.awt.Color(40, 46, 62));
        btnDoiPass.setText("ĐỔI");
        btnDoiPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiPassActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoiPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 180, 70));

        txtNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNewPassword.setForeground(new java.awt.Color(40, 46, 62));
        getContentPane().add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 190, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 139));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Mật khẩu mới:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        txtmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtmail.setForeground(new java.awt.Color(40, 46, 62));
        getContentPane().add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 190, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 139));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 170, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 139));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setText("QUÊN MẬT KHẨU");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        txtma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtma.setForeground(new java.awt.Color(40, 46, 62));
        getContentPane().add(txtma, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 190, 40));

        jLabel8.setBackground(new java.awt.Color(0, 0, 139));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Mã xác nhận:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 170, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/nen02.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(3000, 168));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguiActionPerformed
        // TODO add your handling code here:
        guiMaXacNhan();
    }//GEN-LAST:event_btnguiActionPerformed

    private void btnDoiPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiPassActionPerformed
        // TODO add your handling code here:
         doiMatKhau();
    }//GEN-LAST:event_btnDoiPassActionPerformed

    private void btndongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
            this, "Bạn có chắc muốn thoát ứng dụng?",
            "Xác nhận thoát", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) System.exit(0);
    }//GEN-LAST:event_btndongActionPerformed

    private void btnquaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaylaiActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnquaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                quenmatkhauJdialog dialog = new quenmatkhauJdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiPass;
    private javax.swing.JButton btndong;
    private javax.swing.JButton btngui;
    private javax.swing.JButton btnquaylai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtmail;
    // End of variables declaration//GEN-END:variables
}
