/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App.Main.ChuTro;

import App.DAO.PhongDAO;
import App.DAO.ThongKeDAO;
import App.Entity.Phong;
import App.Impl.PhongDAOImpl;
import App.Impl.ThongKeDAOImpl;
import App.Main.LichSuNguoiDungJDialog;
import App.Main.ThongTinNguoiDungJDialog;
import App.Main.TrangChuChung;
import App.Utils.XAuth;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author WINDOWS
 */
public class Main_ChuTro extends javax.swing.JFrame implements MainChuTroController{

    private final PhongDAO phongDAO = new PhongDAOImpl();
    private final ThongKeDAO thongKeDAO = new ThongKeDAOImpl();
    private DefaultTableModel phongModel;

    public Main_ChuTro() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        buildPhongTable();
        loadAllPhong();
        loadDashboard();
        init();

    }
    
    @Override
    public void init() {
        java.awt.GraphicsEnvironment ge = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment();
        java.awt.Rectangle usableBounds = ge.getMaximumWindowBounds();
        setBounds(usableBounds);
    
    }

    private void buildPhongTable() {
        phongModel = (DefaultTableModel) tblphongtro.getModel();
        phongModel.setColumnIdentifiers(new Object[]{
                "Mã phòng", "Diện tích (m²)", "Giá phòng", "Trạng thái", "Địa chỉ", "Mô tả", "Liên hệ"
        });
        tblphongtro.setRowHeight(26);
    }

    private void loadAllPhong() {
        phongModel.setRowCount(0);
        try {
            List<Phong> list = phongDAO.findAll();
            for (Phong p : list) {
                String maPhong   = (p.getMaPhong() == null) ? "" : p.getMaPhong();
                String dienTich  = (p.getDienTich() == null) ? "" :
                        NumberFormat.getNumberInstance(new Locale("vi", "VN")).format(p.getDienTich());
                String giaTien   = (p.getGiaTien() == null) ? "" :
                        NumberFormat.getNumberInstance(new Locale("vi", "VN")).format(p.getGiaTien());
                String trangThai = (p.getTrangThai() == null) ? "" : p.getTrangThai();
                String diaChi    = (p.getDiaChi() == null) ? "" : p.getDiaChi();
                String moTa      = (p.getMoTa() == null) ? "" : p.getMoTa();
                String lienHe    = (p.getLienHe() == null) ? "" : p.getLienHe();

                phongModel.addRow(new Object[]{maPhong, dienTich, giaTien, trangThai, diaChi, moTa, lienHe});
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi tải danh sách phòng: " + ex.getMessage());
        }
    }
    
    private void loadDashboard() {
        try {
            // Tổng doanh thu
            BigDecimal doanhThu = thongKeDAO.getTongDoanhThu();
            String doanhThuStr = (doanhThu == null) ? "" :
            NumberFormat.getNumberInstance(new Locale("vi", "VN")).format(doanhThu);
            lblDoanhSo.setText(doanhThuStr);

            // Số khách
            int soKhach = thongKeDAO.getSoKhachDangThue();
            lblSoKhach.setText(String.valueOf(soKhach));

            // HĐ sắp hết hạn
            int sapHetHan = thongKeDAO.getSoHopDongSapHetHan(30);
            lblHopDong.setText(String.valueOf(sapHetHan));

            // Hóa đơn chưa thanh toán
            int chuaTT = thongKeDAO.getSoHoaDonChuaThanhToan();
            lblHoaDon.setText(String.valueOf(chuaTT));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnView = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblThangDoanhSo = new javax.swing.JLabel();
        lblDoanhSo = new javax.swing.JLabel();
        lblDoanhSo1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblHopDong = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblSoKhach = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblphongtro = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTrangChu = new javax.swing.JMenu();
        jMenuPhongTro = new javax.swing.JMenu();
        jMenuHopDong = new javax.swing.JMenu();
        jMenuHoaDon = new javax.swing.JMenu();
        jMtaikhoan = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenu();
        jMenuNguoiDung = new javax.swing.JMenu();
        jMenuThongTin = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuLichSuHD = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        btnThoat = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        btnDangXuat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpnView.setBackground(new java.awt.Color(40, 46, 62));
        jpnView.setPreferredSize(new java.awt.Dimension(1560, 630));
        jpnView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TỔNG DOANH THU");

        lblThangDoanhSo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblThangDoanhSo.setForeground(new java.awt.Color(255, 205, 31));
        lblThangDoanhSo.setText("01");

        lblDoanhSo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDoanhSo.setForeground(new java.awt.Color(255, 205, 31));
        lblDoanhSo.setText("100,000,000");

        lblDoanhSo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDoanhSo1.setForeground(new java.awt.Color(255, 205, 31));
        lblDoanhSo1.setText("VND");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblThangDoanhSo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblDoanhSo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDoanhSo1)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblThangDoanhSo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoanhSo)
                    .addComponent(lblDoanhSo1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jpnView.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31), 2));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SỐ HỢP ĐỒNG SẮP HẾT HẠN");

        lblHopDong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHopDong.setForeground(new java.awt.Color(255, 205, 31));
        lblHopDong.setText("XX");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(22, 22, 22))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lblHopDong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHopDong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnView.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, -1, 120));

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31), 2));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SỐ KHÁCH TRỌ ĐANG THUÊ");

        lblSoKhach.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSoKhach.setForeground(new java.awt.Color(255, 205, 31));
        lblSoKhach.setText("XX");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(15, 15, 15))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lblSoKhach)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSoKhach)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnView.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, 120));

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31), 2));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("HÓA ĐƠN CHƯA THANH TOÁN");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        lblHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHoaDon.setForeground(new java.awt.Color(255, 205, 31));
        lblHoaDon.setText("XX");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHoaDon)
                .addGap(107, 107, 107))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnView.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, -1, 120));

        tblphongtro.setBackground(new java.awt.Color(207, 243, 243));
        tblphongtro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblphongtro.setForeground(new java.awt.Color(40, 46, 62));
        tblphongtro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblphongtro.setGridColor(new java.awt.Color(255, 255, 255));
        tblphongtro.setSelectionBackground(new java.awt.Color(46, 56, 86));
        tblphongtro.setSelectionForeground(new java.awt.Color(255, 255, 0));
        jScrollPane1.setViewportView(tblphongtro);

        jpnView.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 1010, 310));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/nen02.jpg"))); // NOI18N
        jpnView.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 760));

        jMenuBar1.setBackground(new java.awt.Color(46, 56, 86));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        jMenuBar1.setForeground(new java.awt.Color(40, 46, 62));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(615, 70));

        jMenuTrangChu.setBackground(new java.awt.Color(153, 153, 153));
        jMenuTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jMenuTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/home (1).png"))); // NOI18N
        jMenuTrangChu.setText("Trang chủ");
        jMenuTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuTrangChu.setOpaque(true);
        jMenuTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTrangChuMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuTrangChu);

        jMenuPhongTro.setBackground(new java.awt.Color(153, 153, 153));
        jMenuPhongTro.setForeground(new java.awt.Color(255, 255, 255));
        jMenuPhongTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/home-page.png"))); // NOI18N
        jMenuPhongTro.setText("Phòng trọ");
        jMenuPhongTro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuPhongTro.setOpaque(true);
        jMenuPhongTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPhongTroMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuPhongTro);

        jMenuHopDong.setBackground(new java.awt.Color(153, 153, 153));
        jMenuHopDong.setForeground(new java.awt.Color(255, 255, 255));
        jMenuHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/rent (1).png"))); // NOI18N
        jMenuHopDong.setText("Hợp đồng");
        jMenuHopDong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuHopDong.setOpaque(true);
        jMenuHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHopDongMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHopDong);

        jMenuHoaDon.setBackground(new java.awt.Color(153, 153, 153));
        jMenuHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jMenuHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/bill (1).png"))); // NOI18N
        jMenuHoaDon.setText("Hóa đơn");
        jMenuHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuHoaDon.setOpaque(true);
        jMenuHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHoaDonMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHoaDon);

        jMtaikhoan.setBackground(new java.awt.Color(153, 153, 153));
        jMtaikhoan.setForeground(new java.awt.Color(255, 255, 255));
        jMtaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/Clien list.png"))); // NOI18N
        jMtaikhoan.setText("Tài khoản");
        jMtaikhoan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMtaikhoan.setOpaque(true);
        jMtaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMtaikhoanMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMtaikhoan);

        jMenuAbout.setBackground(new java.awt.Color(153, 153, 153));
        jMenuAbout.setForeground(new java.awt.Color(255, 255, 255));
        jMenuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Icon/Gear.png"))); // NOI18N
        jMenuAbout.setText("About");
        jMenuAbout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuAbout.setOpaque(true);

        jMenuNguoiDung.setForeground(new java.awt.Color(40, 46, 62));
        jMenuNguoiDung.setText("Người dùng");
        jMenuNguoiDung.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuThongTin.setForeground(new java.awt.Color(40, 46, 62));
        jMenuThongTin.setText("Thông tin cá nhân");
        jMenuThongTin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuThongTinMouseClicked(evt);
            }
        });
        jMenuNguoiDung.add(jMenuThongTin);
        jMenuNguoiDung.add(jSeparator5);

        jMenuLichSuHD.setForeground(new java.awt.Color(40, 46, 62));
        jMenuLichSuHD.setText("Lịch sử hoạt động");
        jMenuLichSuHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLichSuHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLichSuHDMouseClicked(evt);
            }
        });
        jMenuNguoiDung.add(jMenuLichSuHD);

        jMenuAbout.add(jMenuNguoiDung);
        jMenuAbout.add(jSeparator4);

        btnThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(40, 46, 62));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jMenuAbout.add(btnThoat);
        jMenuAbout.add(jSeparator6);

        btnDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(40, 46, 62));
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jMenuAbout.add(btnDangXuat);

        jMenuBar1.add(jMenuAbout);

        jMenu2.setBackground(new java.awt.Color(153, 153, 153));
        jMenu2.setOpaque(true);
        jMenu2.setPreferredSize(new java.awt.Dimension(1200, 6));
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, 1560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn muốn đóng ứng dụng?",
                "Thoát",
                JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn muốn đăng xuất?",
                "Đăng xuất",
                JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
        // Đóng cửa sổ hiện tại
        this.dispose();
        // Mở lại màn hình TrangChuChung
        TrangChuChung home = new TrangChuChung();
        home.setLocationRelativeTo(null); // canh giữa màn hình
        home.setVisible(true);
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
      // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jMenuPhongTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPhongTroMouseClicked
        // TODO add your handling code here:
        this.showPhongJDialog(this); 
    }//GEN-LAST:event_jMenuPhongTroMouseClicked

    private void jMenuHopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHopDongMouseClicked
        // TODO add your handling code here:
        this.showHopDongJDialog(this); 
    }//GEN-LAST:event_jMenuHopDongMouseClicked

    private void jMenuHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHoaDonMouseClicked
        // TODO add your handling code here:
        this.showHoaDonJDialog(this); 
    }//GEN-LAST:event_jMenuHoaDonMouseClicked

    private void jMtaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMtaikhoanMouseClicked
        // TODO add your handling code here:
        this.showTaiKhoanJDialog(this); 
    }//GEN-LAST:event_jMtaikhoanMouseClicked

    private void jMenuThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuThongTinMouseClicked
        // TODO add your handling code here:
    // Lấy tên tài khoản nếu có đăng nhập
    String username = null;
    if (App.Utils.XAuth.user != null) {
        username = App.Utils.XAuth.user.getTenTaiKhoan();
    }

    // Mở dialog thông tin người dùng
    ThongTinNguoiDungJDialog dlg = new ThongTinNguoiDungJDialog(this, true, username);
    dlg.setLocationRelativeTo(this); // hiển thị giữa cửa sổ cha
    dlg.setVisible(true);
    }//GEN-LAST:event_jMenuThongTinMouseClicked

    private void jMenuLichSuHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLichSuHDMouseClicked
        // TODO add your handling code here:
    // Lấy tên tài khoản nếu có đăng nhập
    if (XAuth.user == null) {
        JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập!");
        return;
    }
    int maNguoiDung = XAuth.user.getMaNguoiDung(); 
    LichSuNguoiDungJDialog dlg = new LichSuNguoiDungJDialog(this, true);
    dlg.setLocationRelativeTo(this);
    dlg.setVisible(true);
    }//GEN-LAST:event_jMenuLichSuHDMouseClicked

    private void jMenuTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTrangChuMouseClicked
        // TODO add your handling code here:
        loadDashboard();
        loadAllPhong();
    }//GEN-LAST:event_jMenuTrangChuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                // có màu FlatLaf Light - ko màu Nimbus
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_ChuTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_ChuTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_ChuTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_ChuTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main_ChuTro().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Main_ChuTro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnDangXuat;
    private javax.swing.JMenuItem btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHoaDon;
    private javax.swing.JMenu jMenuHopDong;
    private javax.swing.JMenu jMenuLichSuHD;
    private javax.swing.JMenu jMenuNguoiDung;
    private javax.swing.JMenu jMenuPhongTro;
    private javax.swing.JMenu jMenuThongTin;
    private javax.swing.JMenu jMenuTrangChu;
    private javax.swing.JMenu jMtaikhoan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPanel jpnView;
    private javax.swing.JLabel lblDoanhSo;
    private javax.swing.JLabel lblDoanhSo1;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblHopDong;
    private javax.swing.JLabel lblSoKhach;
    private javax.swing.JLabel lblThangDoanhSo;
    private javax.swing.JTable tblphongtro;
    // End of variables declaration//GEN-END:variables
}
